<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cc0a1e21-c620-477c-a9f0-5d365312ec20</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="WebPush" Version="1.0.13" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Nagorik.Tests\**" />
    <Compile Remove="Nagorik.UiTests\**" />
    <Content Remove="Nagorik.Tests\**" />
    <Content Remove="Nagorik.UiTests\**" />
    <None Remove="Nagorik.Tests\**" />
    <None Remove="Nagorik.UiTests\**" />
  </ItemGroup>

</Project>